//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWoLaDLL.WoLaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wfe.mik.uni-pannon.hu/", ConfigurationName="WoLaService.IWoLaService")]
    public interface IWoLaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldById", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WoLaDLL.WoLaService.BasicFault), Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldByIdBasicFaultFault", Name="BasicFault", Namespace="http://schemas.datacontract.org/2004/07/FlowService.WoLa")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.CheckBoxField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.ComputedField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.DateField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.ImageField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.IntegerField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.LabelField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.PictureField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.RadioButtonField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.RealField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.SelectField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.TextField))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WoLaDLL.WoLaService.TimeField))]
        WoLaDLL.WoLaService.Field GetFieldById(int id, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldById", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldByIdResponse")]
        System.Threading.Tasks.Task<WoLaDLL.WoLaService.Field> GetFieldByIdAsync(int id, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/SetFieldValueById", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/SetFieldValueByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WoLaDLL.WoLaService.BasicFault), Action="http://wfe.mik.uni-pannon.hu/IWoLaService/SetFieldValueByIdBasicFaultFault", Name="BasicFault", Namespace="http://schemas.datacontract.org/2004/07/FlowService.WoLa")]
        void SetFieldValueById(int id, string value, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/SetFieldValueById", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/SetFieldValueByIdResponse")]
        System.Threading.Tasks.Task SetFieldValueByIdAsync(int id, string value, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValue", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValueResponse")]
        string GetFieldValue(string documentName, string fieldName, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValue", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValueResponse")]
        System.Threading.Tasks.Task<string> GetFieldValueAsync(string documentName, string fieldName, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetDocumentId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetDocumentIdResponse")]
        int GetDocumentId(string name, int processId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetDocumentId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetDocumentIdResponse")]
        System.Threading.Tasks.Task<int> GetDocumentIdAsync(string name, int processId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetSectionId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetSectionIdResponse")]
        int GetSectionId(string name, int documentId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetSectionId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetSectionIdResponse")]
        System.Threading.Tasks.Task<int> GetSectionIdAsync(string name, int documentId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldIdResponse")]
        int GetFieldId(string name, int sectionId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldIdResponse")]
        System.Threading.Tasks.Task<int> GetFieldIdAsync(string name, int sectionId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldIdByNameAndDocumentId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldIdByNameAndDocumentIdResponse")]
        int GetFieldIdByNameAndDocumentId(string name, int documentId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldIdByNameAndDocumentId", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldIdByNameAndDocumentIdResponse")]
        System.Threading.Tasks.Task<int> GetFieldIdByNameAndDocumentIdAsync(string name, int documentId, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValueByProccessInstace", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValueByProccessInstaceResponse")]
        string GetFieldValueByProccessInstace(int processInstanceId, string documentName, string sectionName, string fieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValueByProccessInstace", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetFieldValueByProccessInstaceResponse")]
        System.Threading.Tasks.Task<string> GetFieldValueByProccessInstaceAsync(int processInstanceId, string documentName, string sectionName, string fieldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetWorkforceByWhereClauseAndSorting", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetWorkforceByWhereClauseAndSortingResp" +
            "onse")]
        WoLaDLL.WoLaService.Workforce[] GetWorkforceByWhereClauseAndSorting(string whereCaluse, string sort);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IWoLaService/GetWorkforceByWhereClauseAndSorting", ReplyAction="http://wfe.mik.uni-pannon.hu/IWoLaService/GetWorkforceByWhereClauseAndSortingResp" +
            "onse")]
        System.Threading.Tasks.Task<WoLaDLL.WoLaService.Workforce[]> GetWorkforceByWhereClauseAndSortingAsync(string whereCaluse, string sort);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWoLaServiceChannel : TestWoLaDLL.WoLaService.IWoLaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WoLaServiceClient : System.ServiceModel.ClientBase<TestWoLaDLL.WoLaService.IWoLaService>, TestWoLaDLL.WoLaService.IWoLaService {
        
        public WoLaServiceClient() {
        }
        
        public WoLaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WoLaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WoLaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WoLaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WoLaDLL.WoLaService.Field GetFieldById(int id, string guid) {
            return base.Channel.GetFieldById(id, guid);
        }
        
        public System.Threading.Tasks.Task<WoLaDLL.WoLaService.Field> GetFieldByIdAsync(int id, string guid) {
            return base.Channel.GetFieldByIdAsync(id, guid);
        }
        
        public void SetFieldValueById(int id, string value, string guid) {
            base.Channel.SetFieldValueById(id, value, guid);
        }
        
        public System.Threading.Tasks.Task SetFieldValueByIdAsync(int id, string value, string guid) {
            return base.Channel.SetFieldValueByIdAsync(id, value, guid);
        }
        
        public string GetFieldValue(string documentName, string fieldName, string guid) {
            return base.Channel.GetFieldValue(documentName, fieldName, guid);
        }
        
        public System.Threading.Tasks.Task<string> GetFieldValueAsync(string documentName, string fieldName, string guid) {
            return base.Channel.GetFieldValueAsync(documentName, fieldName, guid);
        }
        
        public int GetDocumentId(string name, int processId, string guid) {
            return base.Channel.GetDocumentId(name, processId, guid);
        }
        
        public System.Threading.Tasks.Task<int> GetDocumentIdAsync(string name, int processId, string guid) {
            return base.Channel.GetDocumentIdAsync(name, processId, guid);
        }
        
        public int GetSectionId(string name, int documentId, string guid) {
            return base.Channel.GetSectionId(name, documentId, guid);
        }
        
        public System.Threading.Tasks.Task<int> GetSectionIdAsync(string name, int documentId, string guid) {
            return base.Channel.GetSectionIdAsync(name, documentId, guid);
        }
        
        public int GetFieldId(string name, int sectionId, string guid) {
            return base.Channel.GetFieldId(name, sectionId, guid);
        }
        
        public System.Threading.Tasks.Task<int> GetFieldIdAsync(string name, int sectionId, string guid) {
            return base.Channel.GetFieldIdAsync(name, sectionId, guid);
        }
        
        public int GetFieldIdByNameAndDocumentId(string name, int documentId, string guid) {
            return base.Channel.GetFieldIdByNameAndDocumentId(name, documentId, guid);
        }
        
        public System.Threading.Tasks.Task<int> GetFieldIdByNameAndDocumentIdAsync(string name, int documentId, string guid) {
            return base.Channel.GetFieldIdByNameAndDocumentIdAsync(name, documentId, guid);
        }
        
        public string GetFieldValueByProccessInstace(int processInstanceId, string documentName, string sectionName, string fieldName) {
            return base.Channel.GetFieldValueByProccessInstace(processInstanceId, documentName, sectionName, fieldName);
        }
        
        public System.Threading.Tasks.Task<string> GetFieldValueByProccessInstaceAsync(int processInstanceId, string documentName, string sectionName, string fieldName) {
            return base.Channel.GetFieldValueByProccessInstaceAsync(processInstanceId, documentName, sectionName, fieldName);
        }
        
        public WoLaDLL.WoLaService.Workforce[] GetWorkforceByWhereClauseAndSorting(string whereCaluse, string sort) {
            return base.Channel.GetWorkforceByWhereClauseAndSorting(whereCaluse, sort);
        }
        
        public System.Threading.Tasks.Task<WoLaDLL.WoLaService.Workforce[]> GetWorkforceByWhereClauseAndSortingAsync(string whereCaluse, string sort) {
            return base.Channel.GetWorkforceByWhereClauseAndSortingAsync(whereCaluse, sort);
        }
    }
}
