//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luna_interpreter.BPMNEditorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Process", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects")]
    [System.SerializableAttribute()]
    public partial class Process : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.BPMNObject[] BpmnObjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.FlowObject[] FlowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.Pool[] PoolsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.BPMNObject[] BpmnObjects {
            get {
                return this.BpmnObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.BpmnObjectsField, value) != true)) {
                    this.BpmnObjectsField = value;
                    this.RaisePropertyChanged("BpmnObjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.FlowObject[] Flows {
            get {
                return this.FlowsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlowsField, value) != true)) {
                    this.FlowsField = value;
                    this.RaisePropertyChanged("Flows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.Pool[] Pools {
            get {
                return this.PoolsField;
            }
            set {
                if ((object.ReferenceEquals(this.PoolsField, value) != true)) {
                    this.PoolsField = value;
                    this.RaisePropertyChanged("Pools");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BPMNObject", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.Event))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageCatchEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageThrowEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalCatchEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalThrowEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.LinkCatchEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.LinkThrowEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageStartEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalStartEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.NormalStartEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.TerminateEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.NormalEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.Gateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ComplexMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ComplexSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ExclusiveMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ExclusiveSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.InclusiveMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.InclusiveSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.Pin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.UserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SimpleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelMultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SequentialMultipleUserTask))]
    public partial class BPMNObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LaneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LaneUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.Layout LayoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LaneId {
            get {
                return this.LaneIdField;
            }
            set {
                if ((this.LaneIdField.Equals(value) != true)) {
                    this.LaneIdField = value;
                    this.RaisePropertyChanged("LaneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LaneUid {
            get {
                return this.LaneUidField;
            }
            set {
                if ((object.ReferenceEquals(this.LaneUidField, value) != true)) {
                    this.LaneUidField = value;
                    this.RaisePropertyChanged("LaneUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.Layout Layout {
            get {
                return this.LayoutField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutField, value) != true)) {
                    this.LayoutField = value;
                    this.RaisePropertyChanged("Layout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcessId {
            get {
                return this.ProcessIdField;
            }
            set {
                if ((this.ProcessIdField.Equals(value) != true)) {
                    this.ProcessIdField = value;
                    this.RaisePropertyChanged("ProcessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uid {
            get {
                return this.UidField;
            }
            set {
                if ((object.ReferenceEquals(this.UidField, value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowObject", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Flows")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.Association))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SequenceFlow))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.DefaultFlow))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageFlow))]
    public partial class FlowObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToUidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromUid {
            get {
                return this.FromUidField;
            }
            set {
                if ((object.ReferenceEquals(this.FromUidField, value) != true)) {
                    this.FromUidField = value;
                    this.RaisePropertyChanged("FromUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToUid {
            get {
                return this.ToUidField;
            }
            set {
                if ((object.ReferenceEquals(this.ToUidField, value) != true)) {
                    this.ToUidField = value;
                    this.RaisePropertyChanged("ToUid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pool", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".NonFunctional")]
    [System.SerializableAttribute()]
    public partial class Pool : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.Lane[] LanesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.Lane[] Lanes {
            get {
                return this.LanesField;
            }
            set {
                if ((object.ReferenceEquals(this.LanesField, value) != true)) {
                    this.LanesField = value;
                    this.RaisePropertyChanged("Lanes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Layout", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects")]
    [System.SerializableAttribute()]
    public partial class Layout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageCatchEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageThrowEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalCatchEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalThrowEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.LinkCatchEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.LinkThrowEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageStartEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalStartEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.NormalStartEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.TerminateEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MessageEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.NormalEndEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SignalEndEvent))]
    public partial class Event : Luna_interpreter.BPMNEditorService.BPMNObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AttachedTaskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachedTaskUidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AttachedTaskId {
            get {
                return this.AttachedTaskIdField;
            }
            set {
                if ((this.AttachedTaskIdField.Equals(value) != true)) {
                    this.AttachedTaskIdField = value;
                    this.RaisePropertyChanged("AttachedTaskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachedTaskUid {
            get {
                return this.AttachedTaskUidField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedTaskUidField, value) != true)) {
                    this.AttachedTaskUidField = value;
                    this.RaisePropertyChanged("AttachedTaskUid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCatchEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.IntermediateEvents")]
    [System.SerializableAttribute()]
    public partial class MessageCatchEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageThrowEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.IntermediateEvents")]
    [System.SerializableAttribute()]
    public partial class MessageThrowEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignalCatchEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.IntermediateEvents")]
    [System.SerializableAttribute()]
    public partial class SignalCatchEvent : Luna_interpreter.BPMNEditorService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signal {
            get {
                return this.SignalField;
            }
            set {
                if ((object.ReferenceEquals(this.SignalField, value) != true)) {
                    this.SignalField = value;
                    this.RaisePropertyChanged("Signal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignalThrowEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.IntermediateEvents")]
    [System.SerializableAttribute()]
    public partial class SignalThrowEvent : Luna_interpreter.BPMNEditorService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signal {
            get {
                return this.SignalField;
            }
            set {
                if ((object.ReferenceEquals(this.SignalField, value) != true)) {
                    this.SignalField = value;
                    this.RaisePropertyChanged("Signal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkCatchEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.IntermediateEvents")]
    [System.SerializableAttribute()]
    public partial class LinkCatchEvent : Luna_interpreter.BPMNEditorService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkThrowEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.IntermediateEvents")]
    [System.SerializableAttribute()]
    public partial class LinkThrowEvent : Luna_interpreter.BPMNEditorService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStartEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.StartEvents")]
    [System.SerializableAttribute()]
    public partial class MessageStartEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignalStartEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.StartEvents")]
    [System.SerializableAttribute()]
    public partial class SignalStartEvent : Luna_interpreter.BPMNEditorService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signal {
            get {
                return this.SignalField;
            }
            set {
                if ((object.ReferenceEquals(this.SignalField, value) != true)) {
                    this.SignalField = value;
                    this.RaisePropertyChanged("Signal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalStartEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.StartEvents")]
    [System.SerializableAttribute()]
    public partial class NormalStartEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerminateEndEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.EndEvents")]
    [System.SerializableAttribute()]
    public partial class TerminateEndEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageEndEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.EndEvents")]
    [System.SerializableAttribute()]
    public partial class MessageEndEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalEndEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.EndEvents")]
    [System.SerializableAttribute()]
    public partial class NormalEndEvent : Luna_interpreter.BPMNEditorService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignalEndEvent", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Events.EndEvents")]
    [System.SerializableAttribute()]
    public partial class SignalEndEvent : Luna_interpreter.BPMNEditorService.Event {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Signal {
            get {
                return this.SignalField;
            }
            set {
                if ((object.ReferenceEquals(this.SignalField, value) != true)) {
                    this.SignalField = value;
                    this.RaisePropertyChanged("Signal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ComplexMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ComplexSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ExclusiveMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ExclusiveSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelSplitGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.InclusiveMergeGateway))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.InclusiveSplitGateway))]
    public partial class Gateway : Luna_interpreter.BPMNEditorService.BPMNObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexMergeGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.ComplexGateways")]
    [System.SerializableAttribute()]
    public partial class ComplexMergeGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexSplitGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.ComplexGateways")]
    [System.SerializableAttribute()]
    public partial class ComplexSplitGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExclusiveMergeGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.ExclusiveGateways")]
    [System.SerializableAttribute()]
    public partial class ExclusiveMergeGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExclusiveSplitGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.ExclusiveGateways")]
    [System.SerializableAttribute()]
    public partial class ExclusiveSplitGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParallelMergeGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.ParallelGateways")]
    [System.SerializableAttribute()]
    public partial class ParallelMergeGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParallelSplitGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.ParallelGateways")]
    [System.SerializableAttribute()]
    public partial class ParallelSplitGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InclusiveMergeGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.InclusiveGateways")]
    [System.SerializableAttribute()]
    public partial class InclusiveMergeGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InclusiveSplitGateway", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Gateways.InclusiveGateways")]
    [System.SerializableAttribute()]
    public partial class InclusiveSplitGateway : Luna_interpreter.BPMNEditorService.Gateway {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pin", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Pins")]
    [System.SerializableAttribute()]
    public partial class Pin : Luna_interpreter.BPMNEditorService.BPMNObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GatewayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GatewayUidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expression {
            get {
                return this.ExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpressionField, value) != true)) {
                    this.ExpressionField = value;
                    this.RaisePropertyChanged("Expression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GatewayId {
            get {
                return this.GatewayIdField;
            }
            set {
                if ((this.GatewayIdField.Equals(value) != true)) {
                    this.GatewayIdField = value;
                    this.RaisePropertyChanged("GatewayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GatewayUid {
            get {
                return this.GatewayUidField;
            }
            set {
                if ((object.ReferenceEquals(this.GatewayUidField, value) != true)) {
                    this.GatewayUidField = value;
                    this.RaisePropertyChanged("GatewayUid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Tasks")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.UserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SimpleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelMultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SequentialMultipleUserTask))]
    public partial class Task : Luna_interpreter.BPMNEditorService.BPMNObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTask", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Tasks")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SimpleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.MultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelMultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SequentialMultipleUserTask))]
    public partial class UserTask : Luna_interpreter.BPMNEditorService.Task {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DefaultDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EquipmentGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateSectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkforceGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan DefaultDuration {
            get {
                return this.DefaultDurationField;
            }
            set {
                if ((this.DefaultDurationField.Equals(value) != true)) {
                    this.DefaultDurationField = value;
                    this.RaisePropertyChanged("DefaultDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EquipmentGroupId {
            get {
                return this.EquipmentGroupIdField;
            }
            set {
                if ((this.EquipmentGroupIdField.Equals(value) != true)) {
                    this.EquipmentGroupIdField = value;
                    this.RaisePropertyChanged("EquipmentGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateSectionId {
            get {
                return this.TemplateSectionIdField;
            }
            set {
                if ((this.TemplateSectionIdField.Equals(value) != true)) {
                    this.TemplateSectionIdField = value;
                    this.RaisePropertyChanged("TemplateSectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkforceGroupId {
            get {
                return this.WorkforceGroupIdField;
            }
            set {
                if ((this.WorkforceGroupIdField.Equals(value) != true)) {
                    this.WorkforceGroupIdField = value;
                    this.RaisePropertyChanged("WorkforceGroupId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleUserTask", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Tasks")]
    [System.SerializableAttribute()]
    public partial class SimpleUserTask : Luna_interpreter.BPMNEditorService.UserTask {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MultipleUserTask", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Tasks")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.ParallelMultipleUserTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.SequentialMultipleUserTask))]
    public partial class MultipleUserTask : Luna_interpreter.BPMNEditorService.UserTask {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RepeatCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RepeatCount {
            get {
                return this.RepeatCountField;
            }
            set {
                if ((this.RepeatCountField.Equals(value) != true)) {
                    this.RepeatCountField = value;
                    this.RaisePropertyChanged("RepeatCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParallelMultipleUserTask", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Tasks")]
    [System.SerializableAttribute()]
    public partial class ParallelMultipleUserTask : Luna_interpreter.BPMNEditorService.MultipleUserTask {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SequentialMultipleUserTask", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Objects.Tasks")]
    [System.SerializableAttribute()]
    public partial class SequentialMultipleUserTask : Luna_interpreter.BPMNEditorService.MultipleUserTask {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Association", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Flows")]
    [System.SerializableAttribute()]
    public partial class Association : Luna_interpreter.BPMNEditorService.FlowObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromId {
            get {
                return this.FromIdField;
            }
            set {
                if ((this.FromIdField.Equals(value) != true)) {
                    this.FromIdField = value;
                    this.RaisePropertyChanged("FromId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToId {
            get {
                return this.ToIdField;
            }
            set {
                if ((this.ToIdField.Equals(value) != true)) {
                    this.ToIdField = value;
                    this.RaisePropertyChanged("ToId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SequenceFlow", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Flows")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Luna_interpreter.BPMNEditorService.DefaultFlow))]
    public partial class SequenceFlow : Luna_interpreter.BPMNEditorService.FlowObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromId {
            get {
                return this.FromIdField;
            }
            set {
                if ((this.FromIdField.Equals(value) != true)) {
                    this.FromIdField = value;
                    this.RaisePropertyChanged("FromId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToId {
            get {
                return this.ToIdField;
            }
            set {
                if ((this.ToIdField.Equals(value) != true)) {
                    this.ToIdField = value;
                    this.RaisePropertyChanged("ToId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefaultFlow", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Flows")]
    [System.SerializableAttribute()]
    public partial class DefaultFlow : Luna_interpreter.BPMNEditorService.SequenceFlow {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageFlow", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".Flows")]
    [System.SerializableAttribute()]
    public partial class MessageFlow : Luna_interpreter.BPMNEditorService.FlowObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromId {
            get {
                return this.FromIdField;
            }
            set {
                if ((this.FromIdField.Equals(value) != true)) {
                    this.FromIdField = value;
                    this.RaisePropertyChanged("FromId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToId {
            get {
                return this.ToIdField;
            }
            set {
                if ((this.ToIdField.Equals(value) != true)) {
                    this.ToIdField = value;
                    this.RaisePropertyChanged("ToId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lane", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.BPMN" +
        ".NonFunctional")]
    [System.SerializableAttribute()]
    public partial class Lane : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.Layout LayoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PoolIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.Layout Layout {
            get {
                return this.LayoutField;
            }
            set {
                if ((object.ReferenceEquals(this.LayoutField, value) != true)) {
                    this.LayoutField = value;
                    this.RaisePropertyChanged("Layout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PoolId {
            get {
                return this.PoolIdField;
            }
            set {
                if ((this.PoolIdField.Equals(value) != true)) {
                    this.PoolIdField = value;
                    this.RaisePropertyChanged("PoolId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uid {
            get {
                return this.UidField;
            }
            set {
                if ((object.ReferenceEquals(this.UidField, value) != true)) {
                    this.UidField = value;
                    this.RaisePropertyChanged("Uid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.Docu" +
        "ment")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Section", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.Docu" +
        "ment")]
    [System.SerializableAttribute()]
    public partial class Section : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((this.DocumentIdField.Equals(value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/FlowService.Authentication")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Luna_interpreter.BPMNEditorService.UserPermission[] PermissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Luna_interpreter.BPMNEditorService.UserPermission[] Permissions {
            get {
                return this.PermissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PermissionsField, value) != true)) {
                    this.PermissionsField = value;
                    this.RaisePropertyChanged("Permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPermission", Namespace="http://schemas.datacontract.org/2004/07/FlowService.Authentication")]
    [System.SerializableAttribute()]
    public partial class UserPermission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkforceGroup", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.Reso" +
        "urces")]
    [System.SerializableAttribute()]
    public partial class WorkforceGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipmentGroup", Namespace="http://schemas.datacontract.org/2004/07/FlowService.BPMNEditor.DataContracts.Reso" +
        "urces")]
    [System.SerializableAttribute()]
    public partial class EquipmentGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wfe.mik.uni-pannon.hu/", ConfigurationName="BPMNEditorService.IBPMNEditor")]
    public interface IBPMNEditor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcess", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcessResponse")]
        Luna_interpreter.BPMNEditorService.Process GetProcess(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcess", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcessResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Process> GetProcessAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/SaveProcess", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/SaveProcessResponse")]
        int SaveProcess(Luna_interpreter.BPMNEditorService.Process process, bool isValid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/SaveProcess", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/SaveProcessResponse")]
        System.Threading.Tasks.Task<int> SaveProcessAsync(Luna_interpreter.BPMNEditorService.Process process, bool isValid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/DeleteProcess", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/DeleteProcessResponse")]
        void DeleteProcess(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/DeleteProcess", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/DeleteProcessResponse")]
        System.Threading.Tasks.Task DeleteProcessAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcesses", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcessesResponse")]
        Luna_interpreter.BPMNEditorService.Process[] GetProcesses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcesses", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetProcessesResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Process[]> GetProcessesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocuments", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocumentsResponse")]
        Luna_interpreter.BPMNEditorService.Document[] GetDocuments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocuments", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocumentsResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Document[]> GetDocumentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocumentSections", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocumentSectionsResponse")]
        Luna_interpreter.BPMNEditorService.Section[] GetDocumentSections(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocumentSections", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetDocumentSectionsResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Section[]> GetDocumentSectionsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetSectionById", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetSectionByIdResponse")]
        Luna_interpreter.BPMNEditorService.Section GetSectionById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetSectionById", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetSectionByIdResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Section> GetSectionByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetCredentials", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetCredentialsResponse")]
        Luna_interpreter.BPMNEditorService.LoginData GetCredentials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetCredentials", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetCredentialsResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.LoginData> GetCredentialsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroups", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroupsResponse")]
        Luna_interpreter.BPMNEditorService.WorkforceGroup[] GetWorkforceGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroups", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroupsResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.WorkforceGroup[]> GetWorkforceGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroups", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroupsResponse")]
        Luna_interpreter.BPMNEditorService.EquipmentGroup[] GetEquipmentGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroups", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroupsResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.EquipmentGroup[]> GetEquipmentGroupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroup", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroupResponse")]
        Luna_interpreter.BPMNEditorService.WorkforceGroup GetWorkforceGroup(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroup", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetWorkforceGroupResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.WorkforceGroup> GetWorkforceGroupAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroup", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroupResponse")]
        Luna_interpreter.BPMNEditorService.EquipmentGroup GetEquipmentGroup(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroup", ReplyAction="http://wfe.mik.uni-pannon.hu/IBPMNEditor/GetEquipmentGroupResponse")]
        System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.EquipmentGroup> GetEquipmentGroupAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBPMNEditorChannel : Luna_interpreter.BPMNEditorService.IBPMNEditor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BPMNEditorClient : System.ServiceModel.ClientBase<Luna_interpreter.BPMNEditorService.IBPMNEditor>, Luna_interpreter.BPMNEditorService.IBPMNEditor {
        
        public BPMNEditorClient() {
        }
        
        public BPMNEditorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BPMNEditorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPMNEditorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPMNEditorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Luna_interpreter.BPMNEditorService.Process GetProcess(int id) {
            return base.Channel.GetProcess(id);
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Process> GetProcessAsync(int id) {
            return base.Channel.GetProcessAsync(id);
        }
        
        public int SaveProcess(Luna_interpreter.BPMNEditorService.Process process, bool isValid) {
            return base.Channel.SaveProcess(process, isValid);
        }
        
        public System.Threading.Tasks.Task<int> SaveProcessAsync(Luna_interpreter.BPMNEditorService.Process process, bool isValid) {
            return base.Channel.SaveProcessAsync(process, isValid);
        }
        
        public void DeleteProcess(int id) {
            base.Channel.DeleteProcess(id);
        }
        
        public System.Threading.Tasks.Task DeleteProcessAsync(int id) {
            return base.Channel.DeleteProcessAsync(id);
        }
        
        public Luna_interpreter.BPMNEditorService.Process[] GetProcesses() {
            return base.Channel.GetProcesses();
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Process[]> GetProcessesAsync() {
            return base.Channel.GetProcessesAsync();
        }
        
        public Luna_interpreter.BPMNEditorService.Document[] GetDocuments() {
            return base.Channel.GetDocuments();
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Document[]> GetDocumentsAsync() {
            return base.Channel.GetDocumentsAsync();
        }
        
        public Luna_interpreter.BPMNEditorService.Section[] GetDocumentSections(int id) {
            return base.Channel.GetDocumentSections(id);
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Section[]> GetDocumentSectionsAsync(int id) {
            return base.Channel.GetDocumentSectionsAsync(id);
        }
        
        public Luna_interpreter.BPMNEditorService.Section GetSectionById(int id) {
            return base.Channel.GetSectionById(id);
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.Section> GetSectionByIdAsync(int id) {
            return base.Channel.GetSectionByIdAsync(id);
        }
        
        public Luna_interpreter.BPMNEditorService.LoginData GetCredentials() {
            return base.Channel.GetCredentials();
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.LoginData> GetCredentialsAsync() {
            return base.Channel.GetCredentialsAsync();
        }
        
        public Luna_interpreter.BPMNEditorService.WorkforceGroup[] GetWorkforceGroups() {
            return base.Channel.GetWorkforceGroups();
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.WorkforceGroup[]> GetWorkforceGroupsAsync() {
            return base.Channel.GetWorkforceGroupsAsync();
        }
        
        public Luna_interpreter.BPMNEditorService.EquipmentGroup[] GetEquipmentGroups() {
            return base.Channel.GetEquipmentGroups();
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.EquipmentGroup[]> GetEquipmentGroupsAsync() {
            return base.Channel.GetEquipmentGroupsAsync();
        }
        
        public Luna_interpreter.BPMNEditorService.WorkforceGroup GetWorkforceGroup(int id) {
            return base.Channel.GetWorkforceGroup(id);
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.WorkforceGroup> GetWorkforceGroupAsync(int id) {
            return base.Channel.GetWorkforceGroupAsync(id);
        }
        
        public Luna_interpreter.BPMNEditorService.EquipmentGroup GetEquipmentGroup(int id) {
            return base.Channel.GetEquipmentGroup(id);
        }
        
        public System.Threading.Tasks.Task<Luna_interpreter.BPMNEditorService.EquipmentGroup> GetEquipmentGroupAsync(int id) {
            return base.Channel.GetEquipmentGroupAsync(id);
        }
    }
}
